plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  "tag:Name": "terraform-ansible-web"
  instance-state-name: running

compose:
  ansible_host: public_ip_address
  ansible_user: ec2-user
  ansible_ssh_private_key_file: /root/.ssh/aws_vpc_key

